#!/bin/sh -e

# nginx configuration file
if [ ! -f /etc/nginx/conf.d/nginx-processmaker.conf ]
then
	wget -O '/tmp/processmaker.tar.gz' 'https://sourceforge.net/projects/processmaker/files/ProcessMaker/3.1.3/processmaker-'"$PROCESSMAKER_VERSION"'-community.tar.gz/download'
	cp /tmp/nginx-processmaker.conf /etc/nginx/conf.d/nginx-processmaker.conf
fi

# Default configuration file
if [ ! -d /opt/processmaker/workflow ]
then
	
	# download processmaker
	wget -O /tmp/processmaker.tar.gz 'https://sourceforge.net/projects/processmaker/files/ProcessMaker/3.1.3/processmaker-'"$PROCESSMAKER_VERSION"'-community.tar.gz/download'
	
	# extract
	tar -xf /tmp/processmaker.tar.gz -C /opt
	chown -R nginx:www-data /opt/processmaker
	
	cd /opt/processmaker/workflow/engine
	ln -s ../../gulliver/bin/gulliver gulliver
	
	# setup cron job
	echo "*/5 * * * * php -f /opt/processmaker/workflow/engine/bin/cron.php +force" >> /var/spool/cron/crontabs/root
fi

# set default permission for new files
# allow group edit, everyone else read
umask 002

read -p "$*"

# crond
# php-fpm
# nginx

# execute docker command
# exec "$@"
